import { useEffect, useMemo, useState } from 'react'
import { Controls, ReactFlow, type NodeMouseHandler, type ReactFlowInstance } from '@xyflow/react'
import type { SkillNode, SkillTree } from '../../shared/schemas/tree'
import { SkillNodeCard } from '../components/SkillNodeCard'
import { JointNode, LeafNode, StartNode, SubSkillNode, TrunkNode } from '../components/treeNodes'
import { buildFlow, type TreeFlowNode } from '../lib/treeLayout'
import { QuizModal } from '../components/QuizModal'
import { ReviewModal } from '../components/ReviewModal'

const nodeTypes={skill:SkillNodeCard,trunk:TrunkNode,start:StartNode,joint:JointNode,subskill:SubSkillNode,leaf:LeafNode}
export function SkillTreePage({ treeId, initialTree, onReset }:{treeId:string;initialTree:SkillTree;onReset:()=>void}){
 const [tree,setTree]=useState(initialTree);const [selected,setSelected]=useState<SkillNode|null>(null);const [focus,setFocus]=useState<string|null>(null);const [quiz,setQuiz]=useState(false);const [review,setReview]=useState(false);const [rf,setRf]=useState<ReactFlowInstance<TreeFlowNode>|null>(null)
 const flow=useMemo(()=>buildFlow(tree,focus),[tree,focus]);const current=tree.milestones.find(m=>m.status==='current')
 const all=tree.milestones.flatMap(m=>m.nodes);const rate=all.length?Math.round(all.filter(n=>n.status==='done').length/all.length*100):0
 useEffect(()=>{if(!rf)return;const t=setTimeout(()=>{if(focus)rf.fitView({nodes:flow.focusIds.map(id=>({id})),duration:750,padding:.4});else rf.fitView({duration:750,padding:.15})},40);return()=>clearTimeout(t)},[rf,focus]) // eslint-disable-line react-hooks/exhaustive-deps
 const onNodeClick:NodeMouseHandler<TreeFlowNode>=(_,node)=>{if(node.type==='skill'){setSelected(node.data);setFocus(node.id)}}
 const closeDetail=()=>{setSelected(null);setFocus(null)}
 const pass=()=>{const evidence={type:'quiz' as const,passed_at:new Date().toISOString(),detail:{}};setSelected(s=>s?{...s,status:'done',evidence}:s);setTree((t):SkillTree=>({...t,milestones:t.milestones.map(m=>({...m,nodes:m.nodes.map((n):SkillNode=>n.id===selected?.id?{...n,status:'done',evidence}:n).map((n):SkillNode=>n.status==='locked'&&n.prerequisite_ids.every(id=>id===selected?.id||m.nodes.find(x=>x.id===id)?.status==='done')?{...n,status:'unlocked'}:n)}))}))}
 return <main className="tree-page"><header className="app-header"><div className="brand"><span className="brand-mark">↗</span> SKILL PATH</div><div className="goal"><small>YOUR GOAL</small><strong>{tree.goal}</strong></div><button className="reset" onClick={()=>setReview(true)}>振り返り</button><button className="reset" onClick={onReset}>最初から</button></header><div className="map-heading"><div><p className="eyebrow">CURRENT MILESTONE</p><h1>{current?.label??'スキルマップ'}</h1></div><div className="heading-side"><span className="rate-badge">総合達成率: <strong>{rate}%</strong></span><div className="legend"><span>✓ 習得済み</span><span>◆ 挑戦中</span><span>★ 隠しスキル</span><span>🍃 学習ステップ</span></div></div></div><section className="map"><ReactFlow nodes={flow.nodes} edges={flow.edges} nodeTypes={nodeTypes} onInit={setRf} onNodeClick={onNodeClick} onPaneClick={()=>setFocus(null)} nodesDraggable={false} fitView minZoom={.2} maxZoom={1.6}><Controls showInteractive={false}/></ReactFlow></section><aside className={`detail ${selected?'open':''}`}>{selected&&<><button className="close" onClick={closeDetail}>×</button><span className={`detail-icon ${selected.kind}`}>{selected.kind==='hidden'?'★':selected.status==='done'?'✓':'◆'}</span><p className="eyebrow">{selected.kind==='hidden'?'HIDDEN SKILL':'NEXT SKILL'}</p><h2>{selected.label}</h2><p>{selected.how_to_learn}</p>{selected.leaves.length>0&&<div className="leaf-list"><span>学習ステップ（葉）</span>{selected.leaves.map(l=><div key={l.id}><strong>🍃 {l.label}</strong><small>{l.description}</small></div>)}</div>}{selected.related.length>0&&<div className="related-list"><span>関連技術</span>{selected.related.map(r=><div key={r.id}><strong>{r.label}</strong><small>{r.note}</small></div>)}</div>}<div className="status-line"><span>STATUS</span><strong>{selected.status}</strong></div>{selected.status==='done'?<div className="verified">✓ クイズで証明済み{selected.evidence?.passed_at?` ・ ${selected.evidence.passed_at.slice(0,10)}`:''}</div>:selected.status==='locked'?<button className="primary wide" disabled>前のスキルを完了しよう</button>:<button className="primary wide" onClick={()=>setQuiz(true)}>このスキルに挑戦する →</button>}</>}</aside>{quiz&&selected&&<QuizModal treeId={treeId} nodeId={selected.id} label={selected.label} onClose={()=>setQuiz(false)} onPassed={pass}/>}{review&&<ReviewModal treeId={treeId} tree={tree} onClose={()=>setReview(false)}/>}</main>
}
