import { useMemo, useState } from 'react'
import { Controls, ReactFlow, type NodeMouseHandler } from '@xyflow/react'
import type { SkillNode, SkillTree } from '../../shared/schemas/tree'
import { SkillNodeCard } from '../components/SkillNodeCard'
import { JointNode, LeafNode, StartNode, SubSkillNode, TrunkNode } from '../components/treeNodes'
import { buildFlow, type TreeFlowNode } from '../lib/treeLayout'
import { QuizModal } from '../components/QuizModal'

const nodeTypes={skill:SkillNodeCard,trunk:TrunkNode,start:StartNode,joint:JointNode,subskill:SubSkillNode,leaf:LeafNode}
export function SkillTreePage({ treeId, initialTree, onReset }:{treeId:string;initialTree:SkillTree;onReset:()=>void}){
 const [tree,setTree]=useState(initialTree);const [selected,setSelected]=useState<SkillNode|null>(null);const [quiz,setQuiz]=useState(false);const flow=useMemo(()=>buildFlow(tree),[tree]);const current=tree.milestones.find(m=>m.status==='current')
 const onNodeClick:NodeMouseHandler<TreeFlowNode>=(_,node)=>{if(node.type==='skill')setSelected(node.data)}
 const pass=()=>setTree((t):SkillTree=>({...t,milestones:t.milestones.map(m=>({...m,nodes:m.nodes.map((n):SkillNode=>n.id===selected?.id?{...n,status:'done',evidence:{type:'quiz',passed_at:new Date().toISOString(),detail:{}}}:n).map((n):SkillNode=>n.status==='locked'&&n.prerequisite_ids.every(id=>id===selected?.id||m.nodes.find(x=>x.id===id)?.status==='done')?{...n,status:'unlocked'}:n)}))}))
 return <main className="tree-page"><header className="app-header"><div className="brand"><span className="brand-mark">↗</span> SKILL PATH</div><div className="goal"><small>YOUR GOAL</small><strong>{tree.goal}</strong></div><button className="reset" onClick={onReset}>最初から</button></header><div className="map-heading"><div><p className="eyebrow">CURRENT MILESTONE</p><h1>{current?.label??'スキルマップ'}</h1></div><div className="legend"><span>✓ 習得済み</span><span>◆ 挑戦中</span><span>★ 隠しスキル</span></div></div><section className="map"><ReactFlow nodes={flow.nodes} edges={flow.edges} nodeTypes={nodeTypes} onNodeClick={onNodeClick} nodesDraggable={false} fitView minZoom={.2} maxZoom={1.5}><Controls showInteractive={false}/></ReactFlow></section><aside className={`detail ${selected?'open':''}`}>{selected&&<><button className="close" onClick={()=>setSelected(null)}>×</button><span className={`detail-icon ${selected.kind}`}>{selected.kind==='hidden'?'★':selected.status==='done'?'✓':'◆'}</span><p className="eyebrow">{selected.kind==='hidden'?'HIDDEN SKILL':'NEXT SKILL'}</p><h2>{selected.label}</h2><p>{selected.how_to_learn}</p>{selected.leaves.length>0&&<div className="leaf-list"><span>学習ステップ（葉）</span>{selected.leaves.map(l=><div key={l.id}><strong>🍃 {l.label}</strong><small>{l.description}</small></div>)}</div>}{selected.related.length>0&&<div className="related-list"><span>関連技術</span>{selected.related.map(r=><div key={r.id}><strong>{r.label}</strong><small>{r.note}</small></div>)}</div>}<div className="status-line"><span>STATUS</span><strong>{selected.status}</strong></div>{selected.status==='done'?<div className="verified">✓ クイズで証明済み</div>:selected.status==='locked'?<button className="primary wide" disabled>前のスキルを完了しよう</button>:<button className="primary wide" onClick={()=>setQuiz(true)}>このスキルに挑戦する →</button>}</>}</aside>{quiz&&selected&&<QuizModal treeId={treeId} nodeId={selected.id} label={selected.label} onClose={()=>setQuiz(false)} onPassed={pass}/>}</main>
}
