import { useMemo, useState } from 'react'
import { Background, Controls, ReactFlow, type Edge, type NodeMouseHandler } from '@xyflow/react'
import dagre from '@dagrejs/dagre'
import type { SkillNode, SkillTree } from '../../shared/schemas/tree'
import { SkillNodeCard, type SkillFlowNode } from '../components/SkillNodeCard'
import { QuizModal } from '../components/QuizModal'

const nodeTypes={skill:SkillNodeCard}
function layout(tree:SkillTree){const detailed=tree.milestones.flatMap(m=>m.nodes);const g=new dagre.graphlib.Graph().setDefaultEdgeLabel(()=>({}));g.setGraph({rankdir:'LR',nodesep:38,ranksep:90});detailed.forEach(n=>g.setNode(n.id,{width:210,height:68}));const edges:Edge[]=[];detailed.forEach(n=>n.prerequisite_ids.forEach(p=>{g.setEdge(p,n.id);edges.push({id:`${p}-${n.id}`,source:p,target:n.id,animated:n.status==='unlocked',style:{stroke:'#78a9a2',strokeWidth:2}})}));dagre.layout(g);const nodes:SkillFlowNode[]=detailed.map(n=>{const p=g.node(n.id);return{id:n.id,type:'skill',data:n,position:{x:p.x-105,y:p.y-34}}});return{nodes,edges}}
export function SkillTreePage({ treeId, initialTree, onReset }:{treeId:string;initialTree:SkillTree;onReset:()=>void}){
 const [tree,setTree]=useState(initialTree);const [selected,setSelected]=useState<SkillNode|null>(null);const [quiz,setQuiz]=useState(false);const flow=useMemo(()=>layout(tree),[tree]);const current=tree.milestones.find(m=>m.status==='current')
 const onNodeClick:NodeMouseHandler<SkillFlowNode>=(_,node)=>setSelected(node.data)
 const pass=()=>setTree((t):SkillTree=>({...t,milestones:t.milestones.map(m=>({...m,nodes:m.nodes.map((n):SkillNode=>n.id===selected?.id?{...n,status:'done',evidence:{type:'quiz',passed_at:new Date().toISOString(),detail:{}}}:n).map((n):SkillNode=>n.status==='locked'&&n.prerequisite_ids.every(id=>id===selected?.id||m.nodes.find(x=>x.id===id)?.status==='done')?{...n,status:'unlocked'}:n)}))}))
 return <main className="tree-page"><header className="app-header"><div className="brand"><span className="brand-mark">↗</span> SKILL PATH</div><div className="goal"><small>YOUR GOAL</small><strong>{tree.goal}</strong></div><button className="reset" onClick={onReset}>最初から</button></header><div className="map-heading"><div><p className="eyebrow">CURRENT MILESTONE</p><h1>{current?.label??'スキルマップ'}</h1></div><div className="legend"><span>✓ 習得済み</span><span>◆ 挑戦中</span><span>★ 隠しスキル</span></div></div><section className="map"><ReactFlow nodes={flow.nodes} edges={flow.edges} nodeTypes={nodeTypes} onNodeClick={onNodeClick} fitView minZoom={.5} maxZoom={1.5}><Background color="#d7e5e2" gap={24}/><Controls showInteractive={false}/></ReactFlow></section><aside className={`detail ${selected?'open':''}`}>{selected&&<><button className="close" onClick={()=>setSelected(null)}>×</button><span className={`detail-icon ${selected.kind}`}>{selected.kind==='hidden'?'★':selected.status==='done'?'✓':'◆'}</span><p className="eyebrow">{selected.kind==='hidden'?'HIDDEN SKILL':'NEXT SKILL'}</p><h2>{selected.label}</h2><p>{selected.how_to_learn}</p><div className="status-line"><span>STATUS</span><strong>{selected.status}</strong></div>{selected.status==='done'?<div className="verified">✓ クイズで証明済み</div>:selected.status==='locked'?<button className="primary wide" disabled>前のスキルを完了しよう</button>:<button className="primary wide" onClick={()=>setQuiz(true)}>このスキルに挑戦する →</button>}</>}</aside>{quiz&&selected&&<QuizModal treeId={treeId} nodeId={selected.id} label={selected.label} onClose={()=>setQuiz(false)} onPassed={pass}/>}</main>
}
